interface ratedOn @relationshipProperties {
    movieTitle: String!
    rating: Float!
}

interface actedIn @relationshipProperties {
    actorsName: String!
    role: String!
}

interface ratedGenres @relationshipProperties {
    rating: Float!
}
