name: Fetch GraphQL Data

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch data from GraphQL API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation Login($userType: UserType!, $email: String!, $password: String!){ login(userType: $userType, email: $email, password: $password) { token } }", "variables": {"userType": "Professor", "email": "contato@jovensgenios.com", "password": "JGs$cret1971."}}' \
            https://ecs-api-stage.jovensgenios.com/graphql \
            > data.json

      - name: Upload data file
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: data.json

  use-token:
    needs: fetch-data
    runs-on: ubuntu-latest

    steps:
      - name: Download data file
        uses: actions/download-artifact@v2
        with:
          name: data

      - name: Use token to make GraphQL request
        run: |
          token=$(cat data.json | jq -r '.data.login.token')
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $token" \
            -d '{"query": "query GetProfessor{ Professor(email: "contato@jovensgenios.com") { id name email } }"}' \
            https://ecs-api-stage.jovensgenios.com/graphql \
            > users.json
          echo "Professors:"
          cat users.json

      - name: Upload users file
        uses: actions/upload-artifact@v2
        with:
          name: users
          path: users.json
