name: Fetch GraphQL Data

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Fetch data from GraphQL API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation Login($userType: UserType!, $email: String!, $password: String!){ login(userType: $userType, email: $email, password: $password) { token } }", "variables": {"userType": "Professor", "email": "contato@jovensgenios.com", "password": "JGs$cret1971."}}' \
            https://ecs-api-stage.jovensgenios.com/graphql \
            | jq -r '.data.login.token' \
            > token.txt

      - name: Use token to make GraphQL request
        run: |
          token=$(cat token.txt)
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $token" \
            -d '{"query": "query GetProfessor{ Professor(email: "contato@jovensgenios.com") { id name email } }"}' \
            https://ecs-api-stage.jovensgenios.com/graphql \
            | jq -r '.data.Professor[]' \
            > users.txt
          echo "Users:"
          cat users.txt
