name: Fetch GraphQL Data

on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Fetch data from GraphQL API
        run: |
          response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation Login{ login(userType: Admin, email: "contato@jovensgenios.com", password: "JGs$cret1971.") { token } }"}' \
            https://ecs-api-stage.jovensgenios.com/graphql)
          if ["$(echo "$response")" != "null"]; then
            echo "Token:"
            echo "$response" | jq -r '.data.login.token'
            echo "TOKEN=$("$response" | jq -r '.data.login.token')" >> $GITHUB_ENV
          else
            echo "Error: any token was provided"
          fi

      # - name: Use token to make GraphQL request
      #   run: |
      #     token=$(echo "${{ secrets.TOKEN }}")
      #     curl -X POST \
      #       -H "Content-Type: application/json" \
      #       -H "Authorization: Bearer $token" \
      #       -d '{"query": "query GetProfessor{ Professor(email: "contato@jovensgenios.com") { email } }"}' \
      #       https://ecs-api-stage.jovensgenios.com/graphql \
      #       | jq -r '.data.Professor[]' \
      #       > users.json
      #     echo "Users:"
      #     cat users.json
