name: Test fetch token from JG

on: 
  workflow_dispatch:
# Triggers the workflow every minute
#   schedule:
#     - cron: "*/5 * * * *"
    
jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        id: getToken
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with: 
          endpoint: https://ecs-api-stage.jovensgenios.com/graphql
          configuration: '{"method":"POST","body":{"query":"\\n\\t\\t\\t\\t\\tmutation Login($userType: UserType!, $email: String!, $password: String!){\\n\\t\\t\\t\\t\\t\\tlogin(userType: $userType, email: $email, password: $password) {\\n\\t\\t\\t\\t\\t\\t\\ttoken\\n\\t\\t\\t\\t\\t\\t}\\n\\t\\t\\t\\t\\t}\\n          \\t\\t","variables":{"email":"contato@jovensgenios.com","password":"JGs$cret1971.","userType":"Professor"}}}'
          set-output: true
      - name: Show Response
        run: echo ${{ steps.getToken.outputs }}
