name: Test 2 fetch token from JG

on: 
  workflow_dispatch:
# Triggers the workflow every minute
#   schedule:
#     - cron: "*/5 * * * *"
    
jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.14.0
        id: getToken
        with: 
          url: 'https://ecs-api-stage.jovensgenios.com/graphql'
          method: 'POST'
          body: '{\n    "query": "\\n\\t\\t\\t\\t\\tmutation Login($userType: UserType!, $email: String!, $password: String!){\\n\\t\\t\\t\\t\\t\\tlogin(userType: $userType, email: $email, password: $password) {\\n\\t\\t\\t\\t\\t\\t\\ttoken\\n\\t\\t\\t\\t\\t\\t}\\n\\t\\t\\t\\t\\t}\\n          \\t\\t",\n    "variables": {\n      "email": "contato@jovengenios.com",\n      "password": "JGs$cret1971.",\n      "userType": "Professor"\n    }\n  }'
          preventFailureOnNoResponse: 'true'
          ignoreStatusCodes: '401'
      - name: Show Response
        run: echo ${{ steps.getToken.outputs.response }}
