name: Test fetch token from JG

on: 
  workflow_dispatch:
# Triggers the workflow every minute
#   schedule:
#     - cron: "*/5 * * * *"
    
jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        id: getToken
        uses: JamesIves/fetch-api-data-action@v2.2.4
        with: 
          token-endpoint: https://ecs-api-stage.jovensgenios.com/graphql
          token-configuration: '{"method":"POST","body":{"query":"mutation Login{\\n  login(userType: Admin, email: \\"contato@jovensgenios.com\\", password: \\"JGs$cret1971.\\") {\\n    token\\n  }\\n}"}}'

      - name: Show Response
        run: echo ${{ steps.getToken.outputs }}
